name: Build WarungKu APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: npm install

      - name: Create dummy webDir
        run: mkdir -p out

      - name: Remove incomplete Android folder & re-generate
        run: |
          rm -rf android
          npx cap add android

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Copy custom icons
        run: |
          cp -f icons/mipmap-hdpi/* android/app/src/main/res/mipmap-hdpi/
          cp -f icons/mipmap-mdpi/* android/app/src/main/res/mipmap-mdpi/
          cp -f icons/mipmap-xhdpi/* android/app/src/main/res/mipmap-xhdpi/
          cp -f icons/mipmap-xxhdpi/* android/app/src/main/res/mipmap-xxhdpi/
          cp -f icons/mipmap-xxxhdpi/* android/app/src/main/res/mipmap-xxxhdpi/
          echo "=== Verifikasi ==="
          wc -c android/app/src/main/res/mipmap-hdpi/ic_launcher.png

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore

      - name: Build Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/app/my-release-key.keystore \
            -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: warungku-release-apk
          path: android/app/build/outputs/apk/release/app-release*.apk
